language: java
jdk:
  - oraclejdk8

services:
  - docker

before_install:
  # Use docker to get and start a local Apache CouchDB at "2.x" on port 5984
  - docker pull couchdb:2
  - docker run -d -p 5984:5984 --env COUCHDB_USER=$CLOUDANT_USERNAME --env COUCHDB_PASSWORD=$CLOUDANT_PASSWORD couchdb:2

before_script:
  # Make sure CouchDB is up
  - while [ $? -ne 0 ]; do sleep 1 && curl -v http://localhost:5984; done

##########################
### BUILD WITH GRADLE
##########################
script:
- ./gradlew -Dcloudant.account=http://localhost:5984 -Dcloudant.user=$CLOUDANT_USERNAME -Dcloudant.pass=$CLOUDANT_PASSWORD test
