language: java
jdk:
- oraclejdk8

##########################
### BUILD WITH GRADLE
##########################
script:
- ./gradlew -Dcloudant.account=https://$CLOUDANT_ACCOUNT.cloudant.com -Dcloudant.user=$CLOUDANT_USERNAME -Dcloudant.pass=$CLOUDANT_PASSWORD test
